#!/bin/bash
usage() {
cat << EOF
usage: $0 options <topic>
OPTIONS:
  -h                         Show this message
  -z <zookeeper1,zookeeper2> comma separated list of zookeeper host:port pairs. Defaults to localhost:2181
EOF
}
ZOOKEEPERS='localhost:2181'
while getopts “hz:” OPTION
do
     case "${OPTION}" in
         h)
             usage
             exit 1
             ;;
         z)
             ZOOKEEPERS=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done
shift $((OPTIND-1))
if [ $# = 0 ]; then
  usage
  exit 1
fi
TOPIC=$1
kafka-topics --zookeeper ${ZOOKEEPERS}/kafka --topic $TOPIC --create --partitions 2 --replication-factor 2
