#!/bin/bash
usage() {
cat << EOF
usage: $0 options <topic>
OPTIONS:
  -h                         Show this message
  -b <broker1,broker2>       Comma separated list of kafka broker host:port pairs. Defaults to localhost:9092
EOF
}
BROKERS='localhost:9092'
while getopts “hb:” OPTION
do
     case "${OPTION}" in
         h)
             usage
             exit 1
             ;;
         b)
             BROKERS=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done
shift $((OPTIND-1))
if [ $# = 0 ]; then
  usage
  exit 1
fi
TOPIC=$1
DATETIME=$(date "+%Y-%m-%dT%H:%M:%SZ")
for i in $(awk  -F', ' '{printf "{\"id\":\"%s\",\"on\":\"'${DATETIME}'\",\"body\":\"[%s,%s,%s,%s,%s,%s,%s,%s]\"}\n",$1,$2,$3,$4,$5,$6,$7,$8,$9}' test.csv);do
echo $i | kafka-console-producer --broker-list $BROKERS --topic $TOPIC
done
